name: Publish NuGet Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release --no-build
    - name: Push to GitHub Packages
      run: dotnet nuget push "**/*.nupkg" --source https://nuget.pkg.github.com/tomas-rampas/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate