name: 'Test Report'
on:
  workflow_run:
    workflows: ['CI - Code']
    types:
      - completed

permissions:
  statuses: write
  checks: write
  contents: write
  pull-requests: write
  actions: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v6
      with:
        run_id: ${{ github.event.workflow_run.id }}
        name: test-results
        
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test Report
        token: ${{ secrets.GITHUB_TOKEN }}
        artifact: test-results
        path: "**/test-results.trx"                          
        reporter: dotnet-trx
        fail-on-error: true        
